# Generated by Django 5.0.6 on 2024-07-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='lga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
