# Generated by Django 5.0.6 on 2024-07-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censor', '0002_persons_lga_persons_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='nin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
